config/routes.rb
Rails.application.routes.draw do
  devise_for :restaurants, path: 'restaurants', controllers: {sessions: "restaurants/sessions"}
  devise_for :customers, path: 'customers', controllers: {sessions: "customers/sessions"}

  get '/customers/:id' => 'customers#show' 

  get '/' => 'restaurants#home'
  get '/restaurants' => 'restaurants#index'
  get '/restaurants/:id' => 'restaurants#show'
  get '/sign_up' => 'restaurants#sign_up'

 
  get '/cart' => 'customer_meals#index'
  post '/cart' => 'customer_meals#create'
  delete '/cart/:id' => 'customer_meals#destroy'


  get '/meals/new' => 'meals#new'
  post '/meals' => 'meals#create'
  get '/meals/:id' => 'meals#show'
  get '/meals/:id/edit' => 'meals#edit'
  put '/meals/:id' =>'meals#update'
  delete '/meals/:id' => 'meals#destroy'

  get '/orders' => 'orders#index'
  post '/orders' => 'orders#create'
  get '/orders/:id' => 'orders#show'

  get '/new_text' => 'orders#new_text'
  post '/notify_customer' => 'orders#send_text'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RestaurantsOnRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <a class="navbar-brand" href="/restaurants">Restaurants on Rails</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <% if customer_signed_in? %>
        <li class="nav-item">
           <%= link_to("Profile", edit_customer_registration_path, class: "nav-link") %>
         </li>
         <li class="nav-item">
           <%= link_to("Logout", destroy_customer_session_path, method: :delete, class: "nav-link") %>
         </li>
      <% elsif restaurant_signed_in? %>
          <li class="nav-item">
           <%= link_to("#{current_restaurant.email}", edit_restaurant_registration_path, class: "nav-link") %>
         </li>
         <li class="nav-item">
           <%= link_to("Logout", destroy_restaurant_session_path, method: :delete, class: "nav-link") %>
         </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Sign Up", '/sign_up', class: "nav-link" %>
        </li>
      <li class="nav-item">
        <%= link_to "Login", "/customers/sign_in", class: "nav-link" %>
      </li>
    <% end %>
      <li class="nav-item">
        <a class="nav-link" href="/restaurants">Restaurants</a>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
      <li class="nav-item">
        <%= link_to("/cart", class: "nav-link") do %>
          <i class="fas fa-shopping-cart"></i>
        <% end %>
      </li>
    </ul>
        <%= form_tag("/restaurants", class: "form-inline my-2 my-lg-0", method: :get) do %>
          <input class="form-control mr-sm-2" type="search" placeholder="Search Local">
          <button class="btn btn-success my-2 my-sm-0" type="submit">Search</button>          
        <% end %>
      </div>
    </nav>
    <div class="fluid-container" style="margin-top: 5rem;">
      <%= flash_messages %>
      <%= yield %>
    </div>
  </body>
</html>